// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyajxwsocilbyqalgdrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5YWp4d3NvY2lsYnlxYWxnZHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzc1NjUsImV4cCI6MjA2MDAxMzU2NX0.jHmzfRevKBoOjf57NCABAivYsK0YjlMFYVJNhSUEMfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);